### YamlMime:Tutorial
title: Deploying Azure Functions using Visual Studio Team Services
metadata:
  title: Deploying Azure Functions using VSTS
  description: In this quickstart, you'll use learn how to continuosly deploy Azure Functions code with Visual Studio Team Services
  audience: Developer
  level: Beginner
  ms.topic: get-started-article
  nextTutorialHref: numbers-in-csharp
  nextTutorialTitle: 
  ms.custom: mvc
  ms.prod: .net
  ms.technology: devlang-csharp
items:
- durationInMinutes: 5
  content: |
    In this quickstart, you'll use learn how to continuosly deploy Azure Functions code with Visual Studio Team Services.
- title: Deploying Azure Functions using VSTS
 durationInMinutes: 3
  content: |
    [!include[](includes/readme.md)]
- title: Creating Azure Functions in Visual Studio
  durationInMinutes: 4
  content: |
    [!include[](includes/createfunctions.md)]
- content: |
    You've completed this lab.
