### YamlMime:Tutorial
title: Deploying Azure Functions using Visual Studio Team Services
labUrl: https://labondemand.com/AuthenticatedLaunch/40563?providerId=1 
metadata:
  title: Deploying Azure Functions using VSTS
  description: In this quickstart, you'll use learn how to continuosly deploy Azure Functions code with Visual Studio Team Services
  audience: Developer
  level: Beginner
items:
- durationInMinutes: 5
  content: |
    [!include[](includes/overview.md)]
- title: Setting up the environment
  durationInMinutes: 10
  content: |
    [!include[](includes/setupenv.md)]
- title: Create Azure Function in Azure Portal and Visual Studio
  durationInMinutes: 20
  content: |
    [!include[](includes/setupazurefunction.md)]
- title: Setup continuous integration in Team Services
  durationInMinutes: 10
  content: |
    [!include[](includes/setupCI.md)]
- title: Creating a CD pipeline in Team Services
  durationInMinutes: 10
  content: |
    [!include[](includes/SetupCD.md)]
- content: |
    You've completed this lab.
